- hosts: localhost
  become: yes

  pre_tasks:

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Update && Dist-Upgrade the OS via apt
      apt:
        update_cache: yes
        cache_valid_time: 86400 # 1 day
        upgrade: dist
        autoremove: yes
        autoclean: yes

  roles:
    - role: ngetchell.vscode
    - role: ngetchell.vscode
      vars:
        become_user: "{{ user }}"
        vscode_install: false
        vscode_extension:
          - platformio.platformio-ide
          - robole.marky-stats
          - yzhang.markdown-all-in-one
          - ms-vsliveshare.vsliveshare-pack
          - mhutchie.git-graph
    - role: staticdev.signal
    - role: manala.zsh
    - role: manala.ohmyzsh

  tasks:

    ## CAD/CAM Programs ##

    - name: Install FreeCAD from default apt repositorys
      apt:
        name: freecad


    - name: Install OpenSCAD from default apt repositorys
      apt:
        name: openscad

    - name: Install GIMP from default apt repositorys
      apt:
        name: gimp

    - name: Install Inkscape from default apt repositorys
      apt:
        name: inkscape

    ## Backup Programs ##

    ## Writing Programs ##

    - name: Install Sweet Home 3D from default apt repositorys
      apt:
        name: sweethome3d

    - name: Install GNU Octave from default apt repositorys
      apt:
        name: octave


    ## Backup Programs ##

    - name: Install Nextcloud Desktop from default apt repositorys
      apt:
        name: nextcloud-desktop

    - name: Install rsync from default apt repositorys
      apt:
        name:
          - rsync


    ## Writing Programs ##

    - name: Install AsciiDoc from default apt repositorys
      apt:
        name: asciidoc

    - name: Install pdfgrep from default apt repositorys
      apt:
        name: pdfgrep


    ## Coding Programs ##

    - name: Install Vagrant from default apt repositorys
      apt:
        name:
          - vagrant
          - virtualbox

    - name: Install QEMU from default apt repositorys
      apt:
        name: qemu

    - name: Install Arduino IDE from default apt repositorys
      apt:
        name: arduino

    ## Media Programs ##

    - name: Install VLC media player from default apt repositorys
      apt:
        name: vlc

    - name: Install OBS Studio from default apt repositorys
      apt:
        name: obs-studio

    - name: Install Cheese from default apt repositorys
      apt:
        name: cheese


    ## Gaming Programs ##

    - name: Install Steam from default apt repositorys
      apt:
        name: steam

    - name: Install PlayOnLinux from default apt repositorys
      apt:
        name: playonlinux

    - name: Install Lutris from default apt repositorys
      apt:
        name: lutris


    ## Communications Programs ##

    - name: Install Telegram Desktop from default apt repositorys
      apt:
        name: telegram-desktop

    - name: Install Discord from default apt repositorys
      apt:
        name: discord


    ## Learning Programs ##

    - name: Install Anki from default apt repositorys
      apt:
        name: anki


    ## Finance Programs ##

    - name: Install GnuCash from default apt repositorys
      apt:
        name: gnucash


    ## Web Programs ##

    - name: Install Transmission from default apt repositorys
      apt:
        name: transmission

    - name: Install Thunderbird from default apt repositorys
      apt:
        name: thunderbird

    - name: Install Nmap from default apt repositorys
      apt:
        name: nmap



    ## CLI Programs ##

    - name: Install acpi from default apt repositorys
      apt:
        name: acpi

    - name: Install ncdu from default apt repositorys
      apt:
        name: ncdu

    - name: Install tlp from default apt repositorys
      apt:
        name: tlp

    - name: Install tree from default apt repositorys
      apt:
        name: tree

    - name: Install vim from default apt repositorys
      apt:
        name: vim

    - name: Install powertop from default apt repositorys
      apt:
        name: powertop

    - name: Install traceroute from default apt repositorys
      apt:
        name: traceroute



# git config --global user.email "you@example.com"
# git config --global user.name "Your Name"
# echo export MOZ_USE_XINPUT2=1 | sudo tee /etc/profile.d/use-xinput2.sh
# common
# user
# etcher
# lightburn
# zotero # Literaturverwaltung
# typora # MD-Editor
# cisco 
# parsec
# thunderbird
# bitwarden
# neofetch # displays infos about the system in the terminal, very pritty
# Stop the OSK from always popping up when tapping into a text-field with the touchscreen
# -- https://extensions.gnome.org/extension/3222/block-caribou-36/ works but must e installed via firefox?!
# libpam-fprinfd
# active fingerprint auth with sudo pam-auth-update (graphical interaktion needed)
# spotify-client
# xfreerdp
# table top simulator
# inkstitch
# linphone / sip client
# implicitcad
# teamviewer
# unattended-upgraded / apt-listchanges
# davinci resolve
# wireguard
