- hosts: localhost
  become: yes

  pre_tasks:

    - name: Update && Dist-Upgrade the OS via apt
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 86400 # 1 day

  roles:
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - platformio.platformio-ide
          - robole.marky-stats
          - yzhang.markdown-all-in-one
          - ms-vsliveshare.vsliveshare-pack
          - mhutchie.git-graph
    - role: staticdev.signal
    - role: manala.zsh
    - role: manala.ohmyzsh

  tasks:

    ## CAD/CAM Programs ##

    - name: Install FreeCAD from default apt repositorys
      apt:
        name: freecad


    - name: Install OpenSCAD from default apt repositorys
      apt:
        name: openscad

    - name: Install GIMP from default apt repositorys
      apt:
        name: gimp

    - name: Install Inkscape from default apt repositorys
      apt:
        name: inkscape

    ## Backup Programs ##

    ## Writing Programs ##

    ## Coding Programs ##

    - name: Install Vagrant from default apt repositorys
      apt:
        name:
          - vagrant
          - virtualbox

    - name: Install Arduino IDE from default apt repositorys
      apt:
        name: arduino

    ## Media Programs ##

    - name: Install VLC media player from default apt repositorys
      apt:
        name: vlc

    - name: Install OBS Studio from default apt repositorys
      apt:
        name: obs-studio
        

    ## Gaming Programs ##

    - name: Install Steam from default apt repositorys
      apt:
        name: steam


    ## Communications Programs ##

    - name: Install Telegram Desktop from default apt repositorys
      apt:
        name: telegram-desktop

    - name: Install Discord from default apt repositorys
      apt:
        name: discord

    ## Learning Programs ##

    - name: Install Anki from default apt repositorys
      apt:
        name: anki

    ## Finance Programs ##

    - name: Install GnuCash from default apt repositorys
      apt:
        name: gnucash

    ## Web Programs ##

    - name: Install Transmission from default apt repositorys
      apt:
        name: transmission


# git config --global user.email "you@example.com"
# git config --global user.name "Your Name"
# echo export MOZ_USE_XINPUT2=1 | sudo tee /etc/profile.d/use-xinput2.sh
# common
# user
# deepnest
# etcher
# lightburn
# veracrypt
# element
# zotero
# typora
# xournal++
# teams
# zoom
# cisco
# parsec
# among us
# minecraft
# table top simulator
